### ISSUE TITLE
Side menu categories collapsed by default

### ISSUE THREAD

**Issue by codeclanaus** [CODE-CLAN-AUS/clan-uni#23]
in the side menu. the categories better be collapsed by default

**Comment by iMasoud** [comment]
This is how it looks now on mobile:
![image](https://github.com/CODE-CLAN-AUS/clan-uni/assets/9999208/f25d2d0e-17bb-4dd4-beb8-8df9b49aaa00)
![image](https://github.com/CODE-CLAN-AUS/clan-uni/assets/9999208/d5df11c2-1f7d-4ac8-9987-88f6091da665)
